### ISSUE TITLE
Exclude build/classes/main in .ensime file

### ISSUE THREAD

**Issue by zxcvbn97** [ensime/ensime-gradle#13]
Hi there,

Is there any way to exclude `build/classes/main` in `.ensime` file? I'd like to use ensime without building 
my project first. 
This is what I found in my .ensime file. Ensime would not start unless I remove those from the .ensime file.

    :runtime-deps ("build/classes/main" "build/resources/main" ...)

Thanks!

**Comment by fommil** [comment]
ENSIME can't really do anything if you haven't built the project. The indexer will have nothing to index.

That said, you can safely set `runtime-deps` to `nil` because its not really used anymore.

**Comment by coacoas** [comment]
The runtime-deps is not available right now to be set in the model. The
plugin is building it from the sourceSets.main.runtimeClasspath.

If it's not used anymore, I won't generate that setting anymore.  In the
meantime, I guess the workaround is to just remove that setting from the
produced file or set it to nil.

**Comment by zxcvbn97** [comment]
I still see that ensime can autocomplete my classes and method, even if I haven't built my project yet. That's so surprising.

**Comment by rorygraves** [comment]
It tries, it will fall down on uncompleted classes that have not been loaded into a buffer, because the presentation compiler is then unaware of them.

**Comment by fommil** [comment]
What Rory said :-) please read the workflow doc on the wiki.

**Comment by zxcvbn97** [comment]
@rorygraves @fommil Can you send me the link to the workflow doc? THanks

**Comment by fommil** [comment]
its on the emacs wiki https://github.com/ensime/ensime-emacs/wiki (a lot of this needs to be moved server-side)

**Comment by coacoas** [comment]
runtime-deps has been removed from the .ensime file.
