### ISSUE TITLE
Release v2 to maven central

### ISSUE THREAD

**Issue by fatlazycat** [ensime/ensime-gradle#15]
Hi, are you planning on released a non snapshot and 0.2.x to maven central ?

Appears on 0.1.x is on maven central.

Thanks

**Comment by coacoas** [comment]
The latest snapshot has now been released to https://oss.jfrog.org/oss-snapshot-local.  This can be included in your build using the legacy method of including plugins: 

    buildscript {
      repositories { 
        maven { 
          url "https://oss.jfrog.org/oss-snapshot-local"
        }
      }

      dependencies {
        classpath 'net.coacoas.gradle:ensime-gradle:0.2.0-SNAPSHOT'
      }
    }
    apply plugin: 'ensime'

**Comment by coacoas** [comment]
Version 0.2.2 is now available

     plugins { 
        id 'org.ensime.gradle' version '0.2.2'
     }
