### ISSUE TITLE
Custom :formatting-prefs?

### ISSUE THREAD

**Issue by smungee** [ensime/ensime-gradle#20]
Is there an easy way to get the gradle ensime plugin to also add custom formatting prefs for scalariform into the generated .ensime file?

**Comment by coacoas** [comment]
Not at the moment, but it would be great.

**Comment by coacoas** [comment]
I was out for the weekend, but now I'm back and researching the request. Are you aware of any existing Scalariform plugins for Gradle where we can just use the same configuration?  I briefly looked online, and couldn't find much, and not anything with documentation.  

If one does not exist, I'd probably just add a configuration in the ensime block where you could set the values directly. They would then just get copied directly to the :formatting-prefs form in the .ensime file.

**Comment by coacoas** [comment]
Clicked the wrong button. This issue is definitely not closed.

**Comment by smungee** [comment]
I can't find any good scalariform plugins for gradle either. I basically depend on ensime-emacs's auto-format keybindings (C-c C-v f), and that seems to honor `:formatting-prefs`. Adding a configuration in the ensime block, and copying them directly into the generated .ensime file would be great and would work great for now.

**Comment by smungee** [comment]
Awesome, is there an upcoming release version that will include this? I can try it with my setup..

**Comment by coacoas** [comment]
I will try to get it deployed today.  If you'd like to try it sooner, the code is in my fork at coacoas/ensime-gradle.  

    git clone https://github.com/coacoas/ensime-gradle.git
    cd ensime-gradle
    gradlew clean check publishToMavenLocal

and then load the locally built plugin in your build.gradle file: 

    buildscript { 
      repositories { 
        mavenLocal()
      }

      dependencies {
        classpath 'net.coacoas.gradle:ensime-gradle:0.2.3-SNAPSHOT'
      }
    }

    ensime { 
        formattingPrefs { 
            indentSpaces 2
            indentWithTabs false
        }
    }

That would be a huge help to make sure I did everything correctly.  But I'll at least get a SNAPSHOT version out to jcenter today.

**Comment by coacoas** [comment]
0.2.3-SNAPSHOT has been deployed.  You can grab it in your build.gradle using the buildscript format: 

    buildscript {
        repositories {
            maven {
                url 'https://oss.jfrog.org/oss-snapshot-local'
            }
        }
        dependencies {
            classpath 'net.coacoas.gradle:ensime-gradle:0.2.3-SNAPSHOT'
        }
    }

**Comment by smungee** [comment]
@coacoas Awesome, I'm testing this now. I added the buildscript stuff, but it says "Plugin with id 'ensime' not found", when I do a "apply plugin: 'ensime". Any ideas?

**Comment by smungee** [comment]
Never mind, found that it should be `apply plugin: "org.gradle.ensime"`

**Comment by coacoas** [comment]
Yes -- sorry about that.  The plugin ID changed to match what was required by the Gradle Plugin infrastructure, so it is now 

    apply plugin: 'org.ensime.gradle'

**Comment by smungee** [comment]
Works great! Thanks so much. :)

**Comment by coacoas** [comment]
Great!  I'll go ahead and release an official 0.2.3 at some point tonight.

**Comment by aemoncannon** [comment]
Hey this is awesome. Someday I would like to do an android-on-ensime post...

**Comment by fommil** [comment]
@aemoncannon how about a page on http://ensime.org ? Maybe we need a "Supported platforms" page for JVM / JS / Android

**Comment by fommil** [comment]
@soc might actually want to help with that ^^^ he was really keen to highlight Android support at scala-lang.org and ended up forking the website :smile: to http://get-scala.org/

**Comment by coacoas** [comment]
It sounds great!  I don't do android development myself, so I may not be the best resource.  Maybe @rolandtritsch could help with it. 

I'm going to close this issue, though.  Let's create an issue for ensime/ensime.github.io for the documentation question.
