### ISSUE TITLE
LICENSE file needed

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-gradle#21]
we appear to be completely lacking license information.

Can you please add a `LICENSE` file. All the other build tool plugins are using the permissive free software license Apache 2.0: http://www.apache.org/licenses/LICENSE-2.0.txt

If you both @coacoas @rolandtritsch  agree to that, I'll set up a CLA for all contributors to sign.

**Comment by fommil** [comment]
of course, I'd be happier a copyleft license, as always :wink:

**Comment by coacoas** [comment]
I added a LICENSE file and created a pull request, but I think I created a new issue #22, also.  In any case, I rather like Apache, so that's what I added.  So long as @rolandtritsch is good with it, we can merge it in.
