### ISSUE TITLE
move docs/readme to ensime.org

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-gradle#25]
we are trying to consolidate all docs. Please move your README to http://ensime.github.io/build_tools/gradle/ and follow the README convention e.g. https://raw.githubusercontent.com/ensime/ensime-server/master/README.md

the other half of https://github.com/ensime/ensime.github.io/issues/8

**Comment by fommil** [comment]
@coacoas don't forget about this one :smile: i've noticed you updating the docs... if you could migrate fully over to the website that'd be great.

**Comment by coacoas** [comment]
Yeah, I'm planning on spending some time tonight cleaning things up and this (and #8) are part of that plan.

**Comment by fommil** [comment]
something I'd really like to do for ensime-sbt (and you can easily beat me to it in gradle...) is to have a section that explains how to use gradle as part of a scala workflow in an editor agnostic manner. Perhaps a small section about how to integrate that in emacs.

**Comment by coacoas** [comment]
Yeah, that's an important part of the process.  I'll look into adding that at some point shortly (maybe create another issue for it).  I saw that there's a workflow description under the emacs section that describes how to work with ENSIME/emacs/sbt - is that similar to what you're looking for, just from a build tool perspective?

**Comment by fommil** [comment]
That workflow page will become editor and build tool agnostic.

**Comment by fommil** [comment]
Don't forget to actually remove the docs from README otherwise it'll still be confusing for users to know which one to use.
