### ISSUE TITLE
Provided compile options are not supported

### ISSUE THREAD

**Issue by coacoas** [ensime/ensime-gradle#48]
From the Gitter channel: 

Jonas Jarutis @jarutis 09:55
Hi!
Maybe somebody will give me a hint on a problem.
I've updated ensime from pretty old version and now it does not add provided dependancies. I have a top level project and a subproject spark those dependancies are defined in that subproject.
To add ensime to the project I just added a snippet from http://ensime.github.io/build_tools/gradle/ to gradle.init. Previously I had ensime added to the subproject directly (maybe that is the problem).

Bill Carlson @coacoas 11:12
Are you using providedCompile in a war project, or the (new and not necessarily tested) compileOnly configuration in the Java plugin? Can you share your build.gradle?

**Comment by jarutis** [comment]
Hi, Thanks for a quick response!
Here is our setup: https://gist.github.com/jarutis/1b8aedf5b13146c52a6e5cb9e2a2feca

**Comment by coacoas** [comment]
Yeah, if you could come up with a minimal reproducible case, that would be greatly appreciated.  I think I can see where it is, so I'll try some things, but I would love to get it distilled to the minimal case.

**Comment by coacoas** [comment]
@jarutis I just published a 0.2.8-SNAPSHOT that might address the issue.  Can you give it a try and see if it works?

**Comment by jarutis** [comment]
Works fine. Big thanks.

**Comment by coacoas** [comment]
Great!  I'll publish this as 0.2.8 in a few minutes.  Thanks!
