### ISSUE TITLE
Plugin does not support Android

### ISSUE THREAD

**Issue by rolandtritsch** [ensime/ensime-gradle#5]
Hi all, 

I am working on a project doing Scala development on Android using Gradle and the [gradle-android-scala-plugin](https://github.com/saturday06/gradle-android-scala-plugin).

To test this I am [porting the (gradle based) Android UI samples to Scala](https://github.com/rolandtritsch/scala-android-ui-samples).

Right now the plugin does not create a correct .ensime file when used in this setup.

Any objections to me forking the repo and trying to make this work?

Regards ...
    Roland

**Comment by rolandtritsch** [comment]
Hi Bill, as a first step I added a more complete test-case for Scala and made that work. Pull request incoming. - RT

**Comment by coacoas** [comment]
Hi, Roland.  Sorry I haven't responded. I've been under the weather. 

I *love* forks and pull requests!  I can't wait to see what you find.  I haven't done any Scala/Android development myself, but I'm happy to help where I can.

**Comment by rolandtritsch** [comment]
Hi Bill, so far I have added a more complete test case for scala. Now I am
crawling through the code of the android plugin. Might have something by
the end of the weekend. - RT

On 19 January 2015 at 16:37, Bill Carlson <notifications@github.com> wrote:

> Hi, Roland. Sorry I haven't responded. I've been under the weather.
>
> I *love* forks and pull requests! I can't wait to see what you find. I
> haven't done any Scala/Android development myself, but I'm happy to help
> where I can.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coacoas/gradle-ensime/issues/5#issuecomment-70522867>.
>



-- 
e: roland@tritsch.org
m: +353-86-8563975
s: rolandtritsch
---
http://trits.ch/rt-qr-code
http://trits.ch/rt-linked-in
http://www.tritsch.org
