### ISSUE TITLE
'java-home' variable is not defined.

### ISSUE THREAD

**Issue by Shtucer** [ensime/ensime-gradle#7]
`cd ~/Projects/AwesomeProject
gradle ensime`

.ensime file exists and looks good, but in Emacs
`M-x ensime`
report error "wrong-type-argument stringp nil". Googling point me to ":java-home" variable. Put
`:java-home "full-path-to-java-home"` into .ensime solves problem.

gradle-ensime builds from sources (java 1.7)

Sorry for my terrible English.

**Comment by Shtucer** [comment]
gradle-ensime/src/main/groovy/net/coacoas/gradle/plugins/EnsimeTask.groovy
add 'java-home' : System.properties.'java.home' into properties:

'Map<String, Object> properties = [
                    'root-dir': project.rootDir.absolutePath,
                    'cache-dir': new File(project.buildDir, 'ensime_cache').absolutePath,
                    'name': project.name,
                    'scala-version': scalaLibraryVersion(),
                    'java-home' : System.properties.'java.home'
            ]'

Is this correct way?

**Comment by rolandtritsch** [comment]
Hi Shtucer, yes this is an issue.

The ensime-server behaviour changed recently. :java-home is required now.

https://github.com/ensime/ensime-server/issues/885

I will create a pull request and to make sure that going forward :java-home must be set.

Just checkout the [example](https://gist.github.com/rolandtritsch/8800fdc6d13ae64ff2ba) build file.

**Comment by Shtucer** [comment]
Thanks!
