### ISSUE TITLE
move to ensime organisation

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-gradle#9]
Hi, would you like to move this repo to the ensime organisation? Both in terms of github and to the maven artefact `org.ensime` :-) We'll make you an admin of the repo, of course.

I am starting a new contract with a team that uses gradle, so I'll be needing to make sure this plugin is kept up to date with the config format.

If you would like to do so, just transfer ownership of the repo to me `fommil` and then I (as an "owner" of `ensime`) can transfer to the organisation (for some weird reason it won't be possible for you to transfer directly to `ensime`).

**Comment by coacoas** [comment]
This sounds like a great idea. Honestly, I've let this sit stagnant for far too long. The irony, of course, is that I just found a reason to start work on it again.  :)

Would you like it renamed to ensime-gradle first?

**Comment by fommil** [comment]
I can do that. I probably won't touch it for a few weeks to be honest until I learn how to use gradle (and a little groovy).

**Comment by coacoas** [comment]
OK. I'll transfer to you in a few minutes.

**Comment by coacoas** [comment]
I went ahead and renamed it. The transfer is underway.

**Comment by fommil** [comment]
Thanks!!

**Comment by coacoas** [comment]
Looks good. I guess the next steps are to figure out how to publish this as an "org.ensime" artifact, and then get that automated.

**Comment by fommil** [comment]
I'll give you merge access, the `org.ensime` thing can come later. What I'll do (eventually, give me a few weeks) is automate the publication of snapshots from the CI which will run in drone (I'll need to update the docker image). Then when that's working, we ask sonatype to give you permission to publish to that organisation/artefact so you can make final releases (we'll just typically do that when it feels natural to do so, or either of us needs one urgently for work purposes).
